### ISSUE TITLE
Hardware Recommendation

### ISSUE THREAD

**Issue by S1MP50N** [SoftwareSteve/YaleTranceiver#1]
Hi @SoftwareSteve, 

I was wondering if you could provide any recommendation on the rx module to use alongside this script? 

Any assistance appreciated.

Thanks,

**Comment by SoftwareSteve** [comment]
Don't use the cheap rx modules with the inductor on the board, they are noisy so very short range. The one I used came from Farnel but they don't do them anymore. Look for ones about £10 with a screening can over the Rx chip. The last one I bought came from Amazon labelled as DG0035 (Wingoneer RXB6 £8.99) but I have not tried it yet. Hope that helps.

**Comment by S1MP50N** [comment]
Perfect, thanks for the recommendations, I will dig around and see what I can get my hands on.
